# Generated by Django 5.2.5 on 2025-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
