# Generated by Django 5.2.8 on 2025-12-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_maintenancerequest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='rent',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='type',
        ),
    ]
